### ISSUE TITLE
Issue with Lighthouse doppelganger protection 

### ISSUE THREAD

**Issue by gwenvador** [eth2-educators/eth-docker#287]
I upgraded my client and the doppelganger protection prevented me to start lighthouse to attest. So I disabled it and it worked. I am investigating why this caused this issue. But can you please disable it by default.

**Comment by gwenvador** [comment]
According to lighthouse discord the doppelganger protection can take up to 3 epochs (up to 20 minutes) https://lighthouse-book.sigmaprime.io/validator-doppelganger.html
Lighthouse disables it by default so I think it should be the same here.

**Comment by yorickdowne** [comment]
Doppelganger protection is on by default because I am considerably more concerned about someone getting slashed, than about missing 2 attestations on restart. I'll keep the default out of an abundance of caution.

You can disable it, as you found, and then `git add .` and `git commit` so this change does not interfere with `./ethd update`.
